#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: 
  - Visual Studio 2017
  - Ubuntu
  
environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true

#---------------------------------#
#  Build Script                   #
#---------------------------------#
for:
-
  matrix:
    only:
      - image: Visual Studio 2017
      
  install:
    - ps: pip install mkdocs==0.17.3
    
  build_script:
    - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic
-
  matrix:
    only:
      - image: Visual Studio 2017
      
  install:
    - ps: pip install mkdocs==0.17.3
    
  build_script:
    - ps: .\build.ps1 -Target AppVeyor -Verbosity Diagnostic
-
  matrix:
    only:
      - image: Ubuntu
      
  install:
    - sh: sudo pip install mkdocs==0.17.3
    
  build_script:
    - sh: chmod +x ./build.sh
    - sh: ./build.sh --target AppVeyor --verbosity Diagnostic

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1